name: App
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6  # Añadimos la dependencia de shared_preferences
  google_fonts: ^5.0.0        # Añadimos la dependencia de google_fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
